di.MidiUnavailableException
   Device or resource busy

        MidiOutDevice.java:   -2  com.sun.media.sound.MidiOutDevice/nOpen
        MidiOutDevice.java:   54  com.sun.media.sound.MidiOutDevice/implOpen
   AbstractMidiDevice.java:  154  com.sun.media.sound.AbstractMidiDevice/doOpen
   AbstractMidiDevice.java:  118  com.sun.media.sound.AbstractMidiDevice/open
                  midi.clj:  118  overtone.midi/with-receiver
                  midi.clj:  112  overtone.midi/with-receiver
                  midi.clj:  156  overtone.midi/midi-out
                  midi.clj:  145  overtone.midi/midi-out
                  core.clj: 2646  clojure.core/map/fn
              LazySeq.java:   40  clojure.lang.LazySeq/sval
              LazySeq.java:   49  clojure.lang.LazySeq/seq
                 Cons.java:   39  clojure.lang.Cons/next
                   RT.java:  688  clojure.lang.RT/next
                  core.clj:   64  clojure.core/next
                  core.clj: 3062  clojure.core/nthnext
            core_print.clj:   58  clojure.core/print-sequential
            core_print.clj:  153  clojure.core/fn
            core_print.clj:  153  clojure.core/fn
              MultiFn.java:  233  clojure.lang.MultiFn/invoke
             pr_values.clj:   35  clojure.tools.nrepl.middleware.pr-values/pr-values/fn/reify
    interruptible_eval.clj:  113  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn/fn
                  main.clj:  241  clojure.main/repl/read-eval-print
                  main.clj:  258  clojure.main/repl/fn
                  main.clj:  258  clojure.main/repl
                  main.clj:  174  clojure.main/repl
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   87  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                  AFn.java:  152  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  core.clj:  646  clojure.core/apply
                  core.clj: 1881  clojure.core/with-bindings*
                  core.clj: 1881  clojure.core/with-bindings*
               RestFn.java:  425  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   85  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   55  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  222  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
    interruptible_eval.clj:  190  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                  AFn.java:   22  clojure.lang.AFn/run
   ThreadPoolExecutor.java: 1149  java.util.concurrent.ThreadPoolExecutor/runWorker
   ThreadPoolExecutor.java:  624  java.util.concurrent.ThreadPoolExecutor$Worker/run
               Thread.java:  748  java.lang.Thread/run
